services:
  php:
    build:
      context: "./"
      dockerfile: "./env/php/Dockerfile"
    ports:
      - "3000:3000"
    links:
      - postgres:postgres
#    volumes:
#      - ../:/app
#      - ./php/php.ini:/usr/local/etc/php/php.ini
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/up"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - local-dev

  postgres:
    image: 'citusdata/citus:13-alpine'
    expose:
      - '5432'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    restart: unless-stopped
    networks:
      - local-dev
networks:
  local-dev:

