services:
  php:
    build:
      context: "../"
      dockerfile: "./env/php/Dockerfile"
    expose:
      - "9000"
    ports:
      - "9000:9000"
    links:
      - postgres:postgres
    volumes:
      - ../:/app
      - ./php/php.ini:/usr/local/etc/php/php.ini
    restart: unless-stopped
    networks:
      - local-dev

  nginx:
    build:
      dockerfile: "./nginx/Dockerfile"
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
    volumes:
      - ../:/app
      - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks:
      - local-dev
    links:
      - php:php

  postgres:
    image: 'citusdata/citus:13-alpine'
    expose:
      - '5432'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    restart: unless-stopped
    networks:
      - local-dev

  rabbitmq:
    image: 'rabbitmq:4-management-alpine'
    expose:
      - '5672'
      - '15672'
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: unless-stopped
    networks:
      - local-dev

  redis:
    image: 'redis:8-alpine'
    expose:
      - '6379'
    ports:
      - '6379:6379'
    restart: unless-stopped
    networks:
      - local-dev

networks:
  local-dev:

